### ISSUE TITLE
Derive item subset

### ISSUE THREAD

**Issue by softprops** [softprops/dynomite#107]
## 💡 Feature description

In some cases you don't always want all fields returned in queries when a simple projection will do. Make it easy to derive subset of item attributes 

#### 💻 Basic example

```rust
#[derive(Attributes)]
struct Attrs {
  field: String
}
```

vs 

```rust
#[derive(Item)]
struct Foo {
  #[dynomite(partition_key)]
  id: String,
  field: String
}
```

**Comment by Veetaha** [comment]
Hey, @softprops, may I clarify? Please correct me if I am wrong:

We add an ability to use `#[derive(Attributes)]` only for structs (at least for the first iteration). It will behave exactly like `#[derive(Item)]` but won't require or even prohibit the usage of any of `#[dynomite(partition_key)]` and `#[dynomite(sort_key)]`?
This is what I was looking for not only for projections but also for storing subdocuments without ids.
Then we will have:
```rust
use dynomite::{Item, Attribute};

#[derive(Item)]
struct Book {
    #[dynomite(partition_key)]
    partition_key: Uuid,
    name: String,
}

#[derive(Attribute)]
struct BookNameProjection {
   name: String,
}

async fn get_book(id: Uuid, client: DynamoDbClient) {
     let result = client.get_item(GetItemInput {
            table_name: "Books".to_owned(),
            projection_expression: BookNameProjection::projection_expression(""), // static method accepts root path to prepend to keys
            key: BookKey { partition_key: id }.into(),
            ..Default::default()
     }).await;

     let raw: HashMap<String, Attribute> = result.unwrap().item.unwrap();
     let book: BookNameProjection = raw.from_attr().unwrap();
}
```

This way we will allow having nested objects without ids and more ergonomic projection expressions handling.

**Comment by softprops** [comment]
> It will behave exactly like #[derive(Item)] but won't require or even prohibit the usage of any of #[dynomite(partition_key)] and #[dynomite(sort_key)]?

Not require is the correct phrasing. You can still declare a key if desired. This change would just remove the requirement.


> This way we will allow having nested objects without ids and more ergonomic projection expressions handling.

Correct.

**Comment by softprops** [comment]
I plan on trying to get to thia and a few other attribute changes this week for a new release.

**Comment by softprops** [comment]
fixed in https://github.com/softprops/dynomite/pull/115
