### ISSUE TITLE
How to deal with nested sructures?

### ISSUE THREAD

**Issue by rimutaka** [softprops/dynomite#109]
I'm not sure if this is a bug, my mistake or this has not been implemented yet ...

## 🐛 Bug description
Nested structure 
```
#[derive(Item, Serialize, Deserialize, Debug)]
struct t_list {
    #[dynomite(partition_key)]
    lid: Uuid,
    items: Option<Vec<t_list_item>>,
}
```
fails over `items: Option<Vec<t_list_item>>` with this error message
```
the trait bound `std::option::Option<std::vec::Vec<t_list_item>>: dynomite::Attribute` is not satisfied
the following implementations were found:
  <std::option::Option<T> as dynomite::Attribute>
required by `dynomite::Attribute::from_attr`rustc(E0277)
main.rs(134, 10): Error originated from macro here
```

#### 🤔 Expected Behavior
I was hoping to get the structure similar to this 
```json
{
  "lid": "ff0540dd-3e1c-4977-8d54-5e044688dba1",
  "items": [
    {
      "liid": "30000000-012e-4dd7-9697-dcc06d148a64",
      "title": "... some text ..."
    },
    {
      "liid": "30000001-012e-4dd7-9697-dcc06d148a64",
      "title": "... some text ..."
    }]
}
```

#### 👟 Steps to reproduce

Something as simple as 
```rust
#[derive(Item, Serialize, Deserialize, Debug)]
struct t_list {
    #[dynomite(partition_key)]
    lid: Uuid,
    items: Option<t_list_item>,
}
```
where `t_list_item` is another struct should produce the same error.

#### 🌍 Your environment

`dynomite = {version = "0.8.2", default-features = false, features = ["rustls"]}`

**Comment by rimutaka** [comment]
OK, so I found this 

> Note: Vectors support homogenious collection values. This means the default supported scalars do not permit cases where you need to store a list of heterogenus values. To accomplish this you'll need to implement a wrapper type that represents your desired variants and implement `Attribute` for `YourType`. An `Vec<YourType>` implementation will already be provided

in https://github.com/softprops/dynomite/blob/7667bf9de68fd3c52a91afd55d099d15b5c44952/dynomite/src/lib.rs#L497

and after a lot of trial and error I arrived to this simplified structure and a trait implementation that I struggle to complete ...

```rust
#[derive(Serialize, Deserialize, Debug)]
struct t_item {
    liid: Uuid,
    title: Option<String>,
    description: Option<String>,
}

impl Attribute for t_item {
    // not interested in into_attr
    fn into_attr(self: Self) -> AttributeValue {
        AttributeValue {
            ..AttributeValue::default()
        }
    }
    fn from_attr(value: AttributeValue) -> Result<Self, dynomite::AttributeError> {
        value
            .m
            .ok_or(dynomite::AttributeError::InvalidType)?

// no idea where to past this point ... the following is obviously incorrect ...

            .map(Attribute::from_attr)
            .collect()
    }
}
```

@softprops ,I wonder if you could help me with this snippet or just point me in the right direction.

I'll submit a PR with an example when done. I can imagine it's a pretty common situation.

**Comment by rimutaka** [comment]
OK, so for the nesting to work, there has to be `#[dynomite(partition_key)]` attribute in ALL structures, even if they are deep inside JSON and have no `partition_key`.

```
#[derive(Item, Debug, Serialize, Deserialize)]
struct t_item {
    #[dynomite(partition_key)]
    liid: Uuid,
    title: Option<String>,
}

#[derive(Item, Debug, Serialize, Deserialize)]
struct t_list {
    #[dynomite(partition_key)]
    lid: Uuid,
    items: Option<Vec<t_item>>
}
```

My problem was a missing `#[dynomite(partition_key)]` in `t_item`. Although I figured it out, there are a few problems:

1. this is not clearly documented and there is no explicit example
2. there may be structs with no suitable member to be a valid partition key

**Comment by rimutaka** [comment]
```
thread 'structures_ddb::tests_ddb::tests_ddb::test_dynamodb_get_user_lists' panicked at 'Error converting DDB list into LdList: MissingField { name: "items" }', src/structures_ddb.rs:188:39
```

Would it be a good idea to add "Consider using #[dynomite(default)]."? It doesn't give much details, but should point the user into the right direction.

**Comment by softprops** [comment]
Sure. pulls are welcome
