### ISSUE TITLE
Try trybuild for derive tests

### ISSUE THREAD

**Issue by softprops** [softprops/dynomite#114]
## 💡 Feature description

Would like to know that derive failures fail the way we expect https://docs.rs/trybuild/1.0.30/trybuild/

**Comment by rimutaka** [comment]
That's an interesting library. 
@softprops , I can try building a few test files. Can you give some faulty derive examples we should test?
Some I can think of ...
- missing  #[dynomite(partition_key)]
- missing #[derive(Item)], present #[dynomite(partition_key)] **<-** _not sure this would just be ignored_
- missing #[dynomite(partition_key)] from a nested struct **<-** _not sure this is even tracked or fails silently_
- missing #[derive(Item)] in a nested struct **<-** _not sure this is even tracked or fails silently_

Am I on the right track?

**Comment by softprops** [comment]
That would be great! I'd wait until https://github.com/softprops/dynomite/pull/113 is done first. I'm needing to refactor a bit to make that work.

**Comment by rimutaka** [comment]
Working on it now ...

**Comment by softprops** [comment]
Closing since we have an easy path for this now with https://github.com/softprops/dynomite/pull/116 (nice work!)

Let's try to keep this going with future changes

**Comment by rimutaka** [comment]
If _trybuild_ proves to be of value, I can quickly add it to `aws-lambda-rust-runtime` to test `lambda!` macro error msgs from  https://github.com/awslabs/aws-lambda-rust-runtime/blob/master/lambda-attributes/src/lib.rs. Not sure you want to keep that macro, though. It seems to be redundant.
