### ISSUE TITLE
Unable to insert duo to mio waiting for windows tcp connection

### ISSUE THREAD

**Issue by bottiger** [softprops/dynomite#128]
I am for some reason unable to insert items in dynamodb. I am unsure if this is related to dynomite or some lower level component.

The core of the problem can be understood by looking at this small piece of code. It makes a query, then inserts some data.

```
            let search_key: DynamoSearchKey = String::from("s");

            match query(&f.group_id, Some(&search_key)).await {
                Ok(v) => println!("Query: {:#?}", v),
                Err(e) => panic!("Error completing futures: {}", e),
            }

            match insert_group(&f).await {
                Ok(v) => println!("Inserted: {:#?}", v),
                Err(e) => panic!("Error completing futures: {}", e),
            };
```
The result is that the query runs, but the insert hangs with the following log message (TRACE logging turned on)

> [2020-08-18T07:36:29Z DEBUG hyper::client::connect::dns] resolving host="dynamodb.eu-north-1.amazonaws.com"
> [2020-08-18T07:36:29Z DEBUG hyper::client::connect::http] connecting to 52.94.23.68:443
> [2020-08-18T07:36:29Z TRACE mio::poll] registering with poller
> [2020-08-18T07:36:29Z TRACE mio::sys::windows::selector] register Token(1) Readable | Writable
> [2020-08-18T07:36:29Z TRACE mio::sys::windows::tcp] scheduling a connect

I have attached a more complete log: [fullog.txt](https://github.com/softprops/dynomite/files/5088927/fullog.txt)

I am unsure if this even has something to do with dynomite. It could also be rusotu, hyper, mio, windows or perhaps me :) But I'm starting raising the issue here.
            
dynomite version: 0.9
rustc version: rustc 1.45.2 (d3fb005a3 2020-07-31)

**Comment by softprops** [comment]
@bottiger were you able to resolve the issue?

**Comment by bottiger** [comment]
@softprops Yes, and it was not related to dynamite - or rust in general.

**Comment by bottiger** [comment]
...but I can actually not recall exactly what the problem was
