### ISSUE TITLE
Make tests data-driven and self-updating

### ISSUE THREAD

**Issue by Veetaha** [softprops/dynomite#135]
## 💡 Feature description
Data-driven tests are declarative, they require very little manual maintenance effort and are easy to read.
I propose to use [`expect-test`](http://docs.rs/expect-test), a magic library written by matklad (creator of `rust-analyzer`) to implement this.
The tests are self-updating (i.e. if there is a breaking change in `dynomite` you don't have to manually update the expected values, `expect-test` will modify the source files for you. This is reminiscent of trybuild, which updates the expected stderr value of the test)

#### 💻 Basic example

The test will look like this:
```rust
let actual = Attribute::into_attr(Foo { value: 92 });
// We may add a fmt::Debug newtype on top off attribute value to reduce the verbosity (remove all the None from output)
// When writing new tests we use an empty clause: `expect![[]]`, after that we run the tests for `expect-test` to modify 
// the source file and fill in the expected value Debug representation
let expected = expect![["
    AttributeValue {
        M: Some({
            "value": AttributeValue { 
                 N: Some(92),
                 S: None,
                 ...
             }
        }),
        S: None,
        SS: None,
        ...
    }
"]];
expected.assert_debug_eq(&actual);
```

**Comment by softprops** [comment]
I'd like to make sure we're solving a concrete problem before introducing new dependencies, especially if they are described in terms of magic. Magic often has the side of effect of making code harder to understand for those new to rust and I'd like to keep the codebase as accessible as possible. 

I've personally not yet felt the pain with the simplest approach for the most meaningful behavior, the ability to serialize and deserialize types to and from their equivalent dynamo types [example](https://github.com/softprops/dynomite/blob/8ee63d2bb36ce65bdbd3644fc2153f2b682160fb/dynomite/src/lib.rs#L1220-L1225)

I don't think there's much value in testing Debug strings. I'd rather test the struct values that users interact with and depend on.

> If there is a breaking change in dynomite you don't have to manually update the expected values

As an empathy builder, going through that process is often a helpful exercise for me to understand what pain I would be causing users. I use that as a tool to help weigh the value of a breaking change to determine if it was worth it.

**Comment by Veetaha** [comment]
Hm, I see, I'm closing the issue then
