### ISSUE TITLE
the trait bound `User: From<HashMap<std::string::String, AttributeValue>>` is not satisfied

### ISSUE THREAD

**Issue by marchese29** [softprops/dynomite#165]
## 🐛 Bug description
When I try to use `<Item>::try_from(<Attributes>)` as described in all of the online documentation I can find, I get the following compile-time error: "the trait bound `User: From<HashMap<std::string::String, AttributeValue>>` is not satisfied"

#### 👟 Steps to reproduce
```rust
use dynomite::Item;

#[derive(Item, Clone)]
pub struct User {
    #[dynomite(partition_key)]
    pub key: String,
    pub version: u32,
}

let attrs = ...

let user = User::try_from(attrs);
```

#### 🌍 Your environment

dynomite version: 0.10.0

rustc version:
nightly-x86_64-apple-darwin (default)
rustc 1.57.0-nightly (485ced56b 2021-10-07)

**Comment by Gabotdev** [comment]
Which was your solution?
