### ISSUE TITLE
How to deal with optional attributes?

### ISSUE THREAD

**Issue by samlll42-github** [softprops/dynomite#92]
New to rust and dynomite here, so sorry if it's a dumb question, but I couldn't find any example or documentation on how to deal with optional attributes.  I am used to other libraries/languages where we can specified certain attributes as "nullable" meaning that if they are not set the value is set to null/None.

In other words if I have something like this:
```

[derive(Item, Debug, Clone, GraphQLObject)]
struct Event {
    #[dynomite(partition_key)]
    id: String,
    status: String,
}

```
Some events won't have the attribute status set, for example. When calling Event::from_attrs(result) I am getting a MissingField error, instead of getting a None value.

I tried this too but didn't seem to make a difference:
```

[derive(Item, Debug, Clone, GraphQLObject)]
struct Event {
    #[dynomite(partition_key)]
    id: String,
    status: Option<String>,
}
```

Is there a way to deal with this?

Thanks for the help.

**Comment by softprops** [comment]
Sorry just seeing this now. I'll look into it

**Comment by softprops** [comment]
This seems doable with the ddb `null` type https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes

**Comment by softprops** [comment]
Actually this is already supported for cases where nullable fields are stored with as the `null` ddb type -- https://github.com/softprops/dynomite/blob/aa0b21b91d514d8fb19fdb7504b92342335be56a/dynomite/src/lib.rs#L602-L623

**Comment by softprops** [comment]
Revisiting this there is a separate case here where if you are dealing with a table managed with a different library what omits the field all together, Dynomite doesn't have a good way to deal with that atm

**Comment by rimutaka** [comment]
@softprops Doug, this is a show-stopper for me. Can you help me fix it?
I guess the code responsible for this is here https://github.com/softprops/dynomite/blob/master/dynomite-derive/src/lib.rs#L404

```
Ok(quote! {
            #field_ident: #from_attribute_value(
                attrs.remove(#field_deser_name)
                    .ok_or(::dynomite::AttributeError::MissingField { name: #field_deser_name.to_string() })?
            )?
        })
```

Can we replace ` .ok_or(::dynomite::AttributeError::MissingField { name: #field_deser_name.to_string() })?` with something that returns `None` ?

That will presume that the field is an Option<T> and will still fail if it's not. So if the program expects a missing property it should work just fine otherwise it should fail with the type mismatch at ... runtime or compile time?
Will this change require ALL struct fields to be Option<T>?

It may be more involved than I think. The macro should probably check if the field is an Option before returning an error or None ...

Your advice will be highly appreciated.

**Comment by rimutaka** [comment]
@samlll42-github - did you solve this problem?

**Comment by softprops** [comment]
One potential watch to accommodate this would be to introduce a new field attribute. At the proctor level types are not known, only a syntax ast. Dynomite could introduce something like 

`#[dynomite(default)]` which could fill in the missing field with `Default::default ()`

**Comment by rimutaka** [comment]
Doug, thanks for working in this fix. `#[dynomite(default)]` solves the immediate problem, but my concern is that annotating every optional field with `#[dynomite(default)]` will make the structures very verbose. I wonder if it's possible to return None or Default for Option<T> and Error for everything else if no annotation is present. 

You did mention that the macro knows nothing about the type it generates the trait for, so not sure if a better approach exists.

**Comment by rimutaka** [comment]
**Just an F.Y.I**. ...

One sub-use case to consider is adding a new field to the struct:
- there will be no data for it in the existing DB records
- it is a high probability event in pretty much any application

It doesn't change anything for the current solution, but may have some unexpected implications.

**Comment by softprops** [comment]
That's a good call out generally you have common options there 

1) like sql migrations for relational stores, you can use dynamodb out of application migration that scans a table and backfills data historical data

2) handle in application on a case by case basis updating absent frilds with put operation where useful.
