### ISSUE TITLE
Update to Rusoto 0.43

### ISSUE THREAD

**Issue by bottiger** [softprops/dynomite#96]
I would be nice to update to Rusoto 0.43, but I tried and failed to do it.

**Comment by softprops** [comment]
I'll try take a look at this soon. I haven't been tracking the upstream changes closely to guess what could have gone wrong

**Comment by bottiger** [comment]
I guess  the biggest change in 0.43 is the removal of RusotoFuture in favor of Rust new future library

**Comment by dbasedow** [comment]
The change from RusotoFuture to std::future::Future requires quite a few changes. Right now there's an open PR in futures_backoff that has to land first.

Would you consider splitting dynomite further? The item mapping is already completely independent of the DynamoDbExt and the Retries trait. If there were two separate crates it would be possible to use your awesome item mapping with dynomite-derive and still use the most up to date rusoto version.

**Comment by cedric-h** [comment]
Looking forward to this.

**Comment by softprops** [comment]
have support for this on master. I'll publish it soon

**Comment by softprops** [comment]
published [0.8.0](https://github.com/softprops/dynomite/blob/master/CHANGELOG.md#080) to crates.io
