### ISSUE TITLE
error: the crate `dynomite v0.7.0` depends on crate `rusoto_core v0.41.0` multiple times with different names

### ISSUE THREAD

**Issue by zerofoolcoder** [softprops/dynomite#99]
## 🐛 Bug description
Trying to build my project gives me that weird error. My dependencies are:

[dependencies]
chrono = "0.4"
lambda_runtime = "0.2.1"
log = "0.4"
serde = { version = "1.0.110", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
simple_logger = "1.6.0"
uuid = { version = "0.8.1", features = ["v4"] }
dynomite = {version = "0.7.0", features = ["rustls"]}
rusoto_core = {version = "0.41.0", default_features = false, features=["rustls"]}
rusoto_dynamodb = {version = "0.41.0", default_features = false, features=["rustls"]}

#### 🤔 Expected Behavior
No error message and successful build

#### 👟 Steps to reproduce
Just add the dynomite = {version = "0.7.0", features = ["rustls"]} to the Cargo.toml and run cargo build or cargo check in the terminal

#### 🌍 Your environment
I'm running Fedora 32 Workstation edition on a Thinkpad T480 i7-8650 with 32Gb RAM

dynomite version:
0.7.0

rustc version:
rustc 1.43.1 (8d69840ab 2020-05-04)

**Comment by softprops** [comment]
Cargo has a notion of a default features group. When you request additional features to be enabled without disabling them they remain enabled. Try setting ` default-features = false` as mentioned in the docs
 https://docs.rs/dynomite/0.7.0/dynomite/#rustls

**Comment by zerofoolcoder** [comment]
That was the problem indeed!!!

Thanks a lot (and sorry to bother with this non existing issue)!!!

**Comment by softprops** [comment]
not at all. glad to help
